module.exports = [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Islamabad",
    "Multan",
    "Hyderabad",
    "Gujranwala",
    "Peshawar",
    "Quetta",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Jhang",
    "Rahim Yar Khan",
    "Gujrat",
    "Mardan",
    "Kasur",
    "Dera Ghazi Khan",
    "Mirpur Khas",
    "Nawabshah",
    "Kamoke",
    "Burewala",
    "Jhelum",
    "Sadiqabad",
    "Khanewal",
    "Hafizabad",
    "Kohat",
    "Jacobabad",
    "Shikarpur",
    "Muzaffargarh",
    "Khanpur",
    "Gojra",
    "Mandi Bahauddin",
    "Abbottabad",
    "Dadu",
    "Khuzdar",
    "Ahmedpur East",
    "Daska",
    "Chiniot",
    "Charsadda",
    "Kandhkot",
    "Haripur",
    "Shahdadkot",
    "Kamalia",
    "Tando Adam",
    "Jaranwala",
    "Chishtian",
    "Attock",
    "Vehari",
    "Mianwali",
    "Muzaffarabad",
    "Chakwal",
    "Mandi",
    "Timargara",
    "Hangu",
    "Loralai",
    "Kohlu",
    "Dera Ismail Khan",
    "Badin",
    "Lakki Marwat",
    "Tank",
    "Chaman",
    "Karak",
    "Nankana Sahib",
    "Nushki",
    "Tando Allahyar",
    "Shahdadpur",
    "Zhob",
    "Matiari",
    "Gwadar",
    "Kambar",
    "Badah",
    "Thatta",
    "Naushahro Firoz",
    "Hala",
    "Umerkot",
    "Tando Muhammad Khan",
    "Kotri",
    "Hub",
    "Khairpur",
    "Malakand",
    "Lodhran",
    "Dera Murad Jamali",
    "Gilgit",
    "Sibi",
    "Moro",
    "Dera Bugti",
    "Sujawal",
    "Jamshoro",
    "Pano Aqil",
    "Kandiaro",
    "Kunjah",
    "Turbat",
    "Shahkot",
    "Lala Musa",
    "Ghotki",
    "Harnai",
    "Kotri",
    "Usta Muhammad",
    "Nawabshah",
    "Sakrand",
    "Ratodero",
    "Khipro",
    "Mirpur Khas",
    "Kunri",
    "Nabisar",
    "Ghauspur",
    "Kashmore",
    "Rohri",
    "Jati",
    "Mehar",
    "Bhirkan",
    "Daharki",
    "Sukkur",
    "Gwadar",
    "Khairpur"
];
