import img1 from '../../public/img1.jpg'
import img2 from '../../public/img2.jpg'
import img3 from '../../public/img3.jpg'
import img4 from '../../public/img4.jpg'
import img5 from '../../public/img5.jpg'
import img6 from '../../public/img6.jpg'
import img7 from '../../public/img7.jpg'
import img8 from '../../public/img8.jpg'
import img9 from '../../public/img9.jpg'
import img11 from '../../public/img11.jpg'
import img12 from '../../public/img12.jpg'
import img13 from '../../public/img13.jpg'
import img14 from '../../public/img14.jpg'
import img15 from '../../public/img15.jpg'
import img16 from '../../public/img16.jpg'
import img17 from '../../public/img17.jpg'
import img18 from '../../public/img18.jpg'
import img19 from '../../public/img19.jpg'
import img20 from '../../public/img20.jpg'


export default [img1,img2,img3,img4,img5,img6,img7,img8,img9,img17,img11,img12,img13,img14,img15,img16,img17,img18,img19,img20]